#!/usr/bin/env bash

rm -f $PWD/tmp/pids/server.pid
docker-compose up&
trap "kill -SIGINT $!; wait; echo" INT
if [ -d $HOME/.pow ]; then
  while ! docker-compose port web 3000 >/dev/null 2>&1; do
    sleep 1
  done
  name=$(basename $PWD)
  port=$(docker-compose port web 3000 | cut -d: -f2)
  echo $port > $HOME/.pow/$name
fi
wait
